all:
	cd dotfiles && stow --restow stow
	cd dotfiles && stow --restow home keymaps sh ksh bash zsh git vim htop screen i3 xfce4 conky

clean:
	rm --recursive --force .cache .dbus .local .Xauthority .bash_history .dmenu_cache .sh_history .viminfo
